spring:
  application:
    name: API-GATEWAY
    
#ribbon:
#  ReadTimeout: 60000
#zuul:
##  ribbon:
##    eager-load:
##      enabled: true
##    ReadTimeout: 3000
##    eureka:
##      enabled: true
#        
#  routes:
#    product-service:
#      path: /products/**
#      strip-prefix: false
#      service-id: PRODUCT-SERVICE
      
server:
  port: 9191
  
---
spring:
  cloud:
    gateway:
      routes:
        - id: ORDER-SERVICE
          uri: lb://ORDER-SERVICE
          predicates:
          - Path= /orders/**
          filters:
          - name: CircuitBreaker
            args:
              name: ORDER-SERVICE
              fallbackuri: forward:/orderFallback 
        - id: CART-SERVICE
          uri: lb://CART-SERVICE
          predicates:
          - Path= /cart-items/**
          filters:
          - name: CircuitBreaker
            args:
              name: CART-SERVICE
              fallbackuri: forward:/cartFallback
        - id: PRODUCT-SERVICE
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path= /products/** 
          filters:
          - name: CircuitBreaker
            args:
              name: PRODUCT-SERVICE
              fallbackuri: forward:/productFallback 
       
---
spring:
  cloud:
    gateway:
#      default-filters:
#      - DedupeResponseHeader=Access-Control-Allow-Origin
      globalcors:
        cors-configurations:
          '[/**]':
            allowedHeaders: "*"
            allowedOrigins: "http://localhost:4200"
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
---    
#fallback service response timeout   
hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
            
#---
management:
  endpoints:
    web:
      exposure:
        include: "*"

