server:
  port: 1234

spring:
  application:
    name: COMBINED-SERVICE
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
 
---   
spring:
  datasource:
    url: jdbc:mysql:://localhost/3306/microservices_pokemonshop_combined_service_db
    username: root
    password: root
    
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format-sql: true
    show-sql: true

